### ISSUE TITLE
安装后使用报错了

### ISSUE THREAD

**Issue by hongliangsam** [pasBone/vue-fit-next#14]
![image](https://user-images.githubusercontent.com/50320208/194851603-0fe9eb62-c477-4ff5-b3e7-e08976f48de2.png)
麻烦看看咋回事，谢谢

**Comment by pasBone** [comment]
你好， 看起来应该是不支持 optional chain 导致报错的。建议排查和升级下 @vue/cli-plugin-babel 的版本再试下，如果还是不行的话再贴下package.json的截图哈。

**Comment by hongliangsam** [comment]
@babel/plugin-proposal-optional-chaining配置了还是不得行呢
![image](https://user-images.githubusercontent.com/50320208/194993641-043587c2-78cf-49a1-9032-8d2298f0ad97.png)

package.json
![image](https://user-images.githubusercontent.com/50320208/194993918-272faad5-bedc-4621-9e98-511b3910a570.png)

**Comment by guijue-code** [comment]
我的也是这个问题
![Uploading image.png…]()

**Comment by guijue-code** [comment]
解决啦

**Comment by guijue-code** [comment]
我这边在vue.config.js里加一下mjs的rule,loader使用babel-loader就可以了

**Comment by hongliangsam** [comment]
> 我这边在vue.config.js里加一下mjs的rule,loader使用babel-loader就可以了

贴代码看看，谢谢啦

**Comment by guijue-code** [comment]
<img width="725" alt="image" src="https://user-images.githubusercontent.com/66724249/195024274-1b17b70d-2f6d-42d8-a5eb-e2fca21c0297.png">

**Comment by guijue-code** [comment]
加了个这个就没有报错了，可以正常运行了

**Comment by guijue-code** [comment]
但是功能好像出来了又好像没出来，按住control可以正常缩放页面，但是大屏里的小模块好像没有真正实现缩放

**Comment by pasBone** [comment]
> 但是功能好像出来了又好像没出来，按住control可以正常缩放页面，但是大屏里的小模块好像没有真正实现缩放

刚刚发布了新版本 0.3.1, 麻烦更新下哈。

在此之前没有测试过vue2.x版本的支持能力，看到反馈后立马加上了对vue2.x的支持。

**Comment by guijue-code** [comment]
谢谢啦

**Comment by pasBone** [comment]
> @babel/plugin-proposal-optional-chaining配置了还是不得行呢 ![image](https://user-images.githubusercontent.com/50320208/194993641-043587c2-78cf-49a1-9032-8d2298f0ad97.png)
> 
> package.json ![image](https://user-images.githubusercontent.com/50320208/194993918-272faad5-bedc-4621-9e98-511b3910a570.png)

可以在 vite.config.js 里面添加以下配置... 因为babel默认是排除了node_modules的。

这个方法也可以哈： https://github.com/pasBone/vue-fit-next/issues/14#issuecomment-1274219135

另外添加了对vue2.x的支持，请更新到  v0.3.1
```js
module.exports = {
  transpileDependencies: [
    /[/\\]node_modules[/\\]vue-fit-next[/\\]/,
  ],
  configureWebpack: {
    module: {
      rules: [
        {
          test: /\.mjs$/,
          include: /node_modules/,
          type: "javascript/auto"
        },
      ]
    }
  }
}

```

**Comment by guijue-code** [comment]
额，请问发布好了吗

**Comment by pasBone** [comment]
> 额，请问发布好了吗

发布好了呀。我回复你上一条消息的时候就已经发布好了，你 npm 重新安装下就可以了，版本是0.3.2或者0.3.1

**Comment by guijue-code** [comment]
好的，谢谢啦

**Comment by hongliangsam** [comment]
babel-loder配置了还是不得行，暴力修改源码去掉?.链式写法倒是可以了，但是没效果了。。。
![image](https://user-images.githubusercontent.com/50320208/195042943-df60ad9f-547c-4888-8298-c1edb26fa18f.png)
![image](https://user-images.githubusercontent.com/50320208/195043023-3c946aab-a3a7-4cbf-a106-4b8749f2dfc6.png)

**Comment by pasBone** [comment]
> babel-loder配置了还是不得行，暴力修改源码去掉?.链式写法倒是可以了，但是没效果了。。。 ![image](https://user-images.githubusercontent.com/50320208/195042943-df60ad9f-547c-4888-8298-c1edb26fa18f.png) ![image](https://user-images.githubusercontent.com/50320208/195043023-3c946aab-a3a7-4cbf-a106-4b8749f2dfc6.png)

1、babel.config.js
```js
module.exports = {
  presets: [
    '@vue/cli-plugin-babel/preset'
  ],
  plugins: [
    "@babel/plugin-proposal-optional-chaining",
  ]
}
```

2、 vue.config.js
```js
module.exports = {
  transpileDependencies: [
    /[/\\]node_modules[/\\]vue-fit-next[/\\]/,
  ],
  configureWebpack: {
    module: {
      rules: [
        {
          test: /\.mjs$/,
          include: /node_modules/,
          type: "javascript/auto"
        },
      ]
    }
  }
}
```
设置这两个地方之后是没问题的，我专门使用vue-cli 4.4.4 版本测试过了，请仔细检查下。
如果还不行，建议升级vue-clic版本哈。
