### ISSUE TITLE
vue2.x引入此组件，运行报错

### ISSUE THREAD

**Issue by Grails125** [pasBone/vue-fit-next#17]
报错如下
`error  in ./node_modules/vue-fit-next/dist/index.mjs

Module parse failed: Unexpected token (140:23)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   el.dataset.fit = id;
|   const { arg, value } = binding;
>   const origin = value?.origin || arg || "";
|   const lockX = value?.lockX || false;
|   const lockY = value?.lockY || false;`

**Comment by pasBone** [comment]
参见 #14， optional chian 的配置问题。

**Comment by Grails125** [comment]
感谢，参照里面的方法已解决
